service: authorization-service

frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

functions:
  basicAuthorizer:
    handler: src/basicAuthorizer.basicAuthorizer
